# action.yml
name: 'Estimate Property Price'
description: 'Update your repo with estimated property price!'
inputs:
  uprn:
    description: 'Found by searching on Zoopla'
    required: true
    default: '123456'
outputs:
  testOutput:
    description: 'test output'
  completed:
    description: 'if completed correctly!'
runs:
  using: 'docker'
  image: 'Dockerfile'
